import{a as M,S,i as n}from"./assets/vendor-BjRz3xa9.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))u(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&u(i)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function u(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const q="49795001-63fc88dd531083a7427250d55";async function f(r,e){return await M("https://pixabay.com/api/",{params:{key:q,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:e}})}const g=document.querySelector(".gallery"),y=document.querySelector(".loader"),h=document.querySelector(".load-more");let l=null;function P(r){const{webformatURL:e,largeImageURL:s,tags:u,likes:t,views:o,comments:i,downloads:w}=r;return`<li class="gallery-item">
        <div>
        <a class="gallery-link" href="${s}">
          <img class="gallery-image" src="${e}" alt="${u}" />
        </a>
        </div>
        <ul class="gallery-sublist">
          <li class="gallery-subitem"><p class="sub-text">Likes</p><p class="sub-value">${t}</p></li>
          <li class="gallery-subitem"><p class="sub-text">Views</p><p class="sub-value">${o}</p></li>
          <li class="gallery-subitem"><p class="sub-text">Comments</p><p class="sub-value">${i}</p></li>
          <li class="gallery-subitem"><p class="sub-text">Downloads</p><p class="sub-value">${w}</p></li>
        </ul>
      </li>`}function b(r){const e=r.map(P).join("");g.insertAdjacentHTML("beforeend",e),l?l.refresh():l=new S(".gallery a",{captionsData:"alt",captionDelay:250})}function x(){g.innerHTML="",l&&(l.destroy(),l=null)}function L(){y.classList.remove("hidden")}function v(){y.classList.add("hidden")}function m(){h.classList.add("load-more")}function p(){h.classList.remove("load-more")}function I(){const r=document.querySelector(".gallery-item");if(r){const{height:e}=r.getBoundingClientRect();window.scrollBy({left:0,top:e*3,behavior:"smooth"})}}const a={form:document.querySelector("form"),searchInput:document.querySelector(".input"),loader:document.querySelector(".loader"),loadMore:document.querySelector(".load-more"),gallery:document.querySelector(".gallery")};let c=1,d="";a.form.addEventListener("submit",R);a.loadMore.addEventListener("click",E);a.loadMore.classList.replace("load-more","hidden");function R(r){if(r.preventDefault(),d=r.target.elements.search.value.trim(),c=1,!d){n.warning({position:"topRight",title:"Warning",message:"Please enter a search query"}),a.searchInput.focus();return}L(),m(),x(),p(),f(d,c).then(e=>{const s=e.data;if(!s.hits||s.hits.length===0){n.warning({position:"topRight",title:"Warning",message:"Sorry, no images found. Please try another query!"});return}s.hits.length<s.totalHits?(m(),a.loadMore.classList.replace("load-more-hidden","load-more")):p(),b(s.hits)}).catch(e=>{n.error({position:"topRight",title:"Error",message:"Failed to fetch images. Please try again later."}),console.error("Error:",e)}).finally(()=>{v()}),r.target.reset()}async function E(){c++,a.loadMore.disabled=!0,p(),L();try{const e=(await f(d,c)).data;b(e.hits),I();const s=Math.ceil(e.totalHits/20);c>=s?n.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."}):m()}catch(r){n.error({position:"topRight",title:"Error",message:r.message})}finally{v(),a.loadMore.disabled=!1}}
//# sourceMappingURL=index.js.map
