import{a as L,S as M,i as n}from"./assets/vendor-BjRz3xa9.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))d(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&d(i)}).observe(document,{childList:!0,subtree:!0});function a(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function d(t){if(t.ep)return;t.ep=!0;const o=a(t);fetch(t.href,o)}})();const v="49795001-63fc88dd531083a7427250d55";async function m(r,e){return await L("https://pixabay.com/api/",{params:{key:v,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:e}})}const p=document.querySelector(".gallery"),g=document.querySelector(".loader");let l=null;function w(r){const{webformatURL:e,largeImageURL:a,tags:d,likes:t,views:o,comments:i,downloads:b}=r;return`<li class="gallery-item">
        <div>
        <a class="gallery-link" href="${a}">
          <img class="gallery-image" src="${e}" alt="${d}" />
        </a>
        </div>
        <ul class="gallery-sublist">
          <li class="gallery-subitem"><p class="sub-text">Likes</p><p class="sub-value">${t}</p></li>
          <li class="gallery-subitem"><p class="sub-text">Views</p><p class="sub-value">${o}</p></li>
          <li class="gallery-subitem"><p class="sub-text">Comments</p><p class="sub-value">${i}</p></li>
          <li class="gallery-subitem"><p class="sub-text">Downloads</p><p class="sub-value">${b}</p></li>
        </ul>
      </li>`}function f(r){const e=r.map(w).join("");p.insertAdjacentHTML("beforeend",e),l?l.refresh():l=new M(".gallery a",{captionsData:"alt",captionDelay:250})}function S(){p.innerHTML="",l&&(l.destroy(),l=null)}function h(){g.classList.remove("hidden")}function y(){g.classList.add("hidden")}function q(){const r=document.querySelector(".gallery-item");if(r){const{height:e}=r.getBoundingClientRect();window.scrollBy({left:0,top:e*3,behavior:"smooth"})}}const s={form:document.querySelector("form"),searchInput:document.querySelector(".input"),loader:document.querySelector(".loader"),loadMore:document.querySelector(".load-more"),gallery:document.querySelector(".gallery")};let c=1,u="";s.form.addEventListener("submit",P);s.loadMore.addEventListener("click",x);s.loadMore.classList.replace("load-more","load-more-hidden");function P(r){if(r.preventDefault(),u=r.target.elements.search.value.trim(),c=1,!u){n.warning({position:"topRight",title:"Warning",message:"Please enter a search query"}),s.searchInput.focus();return}h(),S(),s.loadMore.classList.replace("load-more","load-more-hidden"),m(u,c).then(e=>{const a=e.data;if(!a.hits||a.hits.length===0){n.warning({position:"topRight",title:"Warning",message:"Sorry, no images found. Please try another query!"});return}a.hits.length<a.totalHits?s.loadMore.classList.replace("load-more-hidden","load-more"):s.loadMore.classList.replace("load-more","load-more-hidden"),f(a.hits)}).catch(e=>{n.error({position:"topRight",title:"Error",message:"Failed to fetch images. Please try again later."}),console.error("Error:",e)}).finally(()=>{y()}),r.target.reset()}async function x(){c++,s.loadMore.disabled=!0,s.loadMore.classList.replace("load-more","load-more-hidden"),h();try{const e=(await m(u,c)).data;f(e.hits),q();const a=Math.ceil(e.totalHits/15);c>=a?n.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."}):s.loadMore.classList.replace("load-more-hidden","load-more")}catch(r){n.error({position:"topRight",title:"Error",message:r.message})}finally{y(),s.loadMore.disabled=!1}}
//# sourceMappingURL=index.js.map
